### ISSUE TITLE
CRASH!!!!!!

### ISSUE THREAD

**Issue by CesarUlises1996** [JadedPacks/Agrarian-Skies-2#105]
## Steps to Reproduce

1.Making Portal-in-a-Box
2.I just was fixing the insestability of the matrix puting again the items
3.CRASH, screamed a little bit, and i join again
4. I can't play, because the server crash when I'm entering the world

it is possible to delete the item that causes the crash, I have no backup and I know that the server does one every 30min, but I do not intend to do again what I did 30min ago (i mean kill Eldritch Guardians suck "I had to put my sword looting")
## Logs

* Crash Log:

---- Minecraft Crash Report ----
// Don't do that.

Time: 9/16/20 6:59 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at thaumcraft.common.tiles.TileInfusionMatrix.craftCycle(TileInfusionMatrix.java:483)
	at thaumcraft.common.tiles.TileInfusionMatrix.func_145845_h(TileInfusionMatrix.java:224)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- He@d --
Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at thaumcraft.common.tiles.TileInfusionMatrix.craftCycle(TileInfusionMatrix.java:483)
	at thaumcraft.common.tiles.TileInfusionMatrix.func_145845_h(TileInfusionMatrix.java:224)

-- Block entity being ticked --
Details:
	Name: TileInfusionStone // thaumcraft.common.tiles.TileInfusionMatrix
	Block type: ID #502 (tile.blockStoneDevice // thaumcraft.common.blocks.BlockStoneDevice)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-902,60,1011), Chunk: (at 10,3,3 in -57,63; contains blocks -912,0,1008 to -897,255,1023), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Actual block type: ID #502 (tile.blockStoneDevice // thaumcraft.common.blocks.BlockStoneDevice)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: 08_Junio_2020
	All players: 1 total; [EntityPlayerMP['BjergsenKing'/51, l='08_Junio_2020', x=-899.73, y=59.67, z=1014.32]]
	Chunk stats: ServerChunkCache: 630 Drop: 0
	Level seed: 2239003194312966991
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-877,58,1002), Chunk: (at 3,3,10 in -55,62; contains blocks -880,0,992 to -865,255,1007), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 11366645 game time, 13314852 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 16701 (now: true), thunder time: 77453 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP[''/51, l='08_Junio_2020', x=-899.73, y=59.67, z=1014.32]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

Nice support guys :)

## Client Information

* Modpack Version:2.0.6
* Server/LAN/Single Player:Single Player

**Comment by remclave** [comment]
This is the first time anyone has reported this issue. You will have to repeat the process to validate it. Again, no other players have experienced this 'bug.' There IS a backup folder so if you aren't willing to reload from backup to verify it is a bug, I cannot help you.
