### ISSUE TITLE
Game crashes after placing quest reward Energy Cell

### ISSUE THREAD

**Issue by codewarrior0** [JadedPacks/Agrarian-Skies-2#15]
## Steps to Reproduce

1. Claim reward from Energy Cell quest "Power Storage"
2. Place Energy Cell

## Logs

* Crash Log:
```
[07:48:43] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Reading NBT data
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.ClassCastException: net.minecraft.nbt.NBTTagList cannot be cast to net.minecraft.nbt.NBTTagByteArray
	at net.minecraft.nbt.NBTTagCompound.func_74770_j(NBTTagCompound.java:233) ~[dh.class:?]
	at cofh.thermalexpansion.util.helpers.ReconfigurableHelper.getSideCache(ReconfigurableHelper.java:94) ~[ReconfigurableHelper.class:?]
	at cofh.thermalexpansion.block.cell.BlockCell.func_149689_a(BlockCell.java:92) ~[BlockCell.class:?]
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:213) ~[abh.class:?]
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103) ~[abh.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128) ~[add.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
```

## Client Information

* Modpack Version: 2.0.0
* Single Player

**Comment by a1d4r** [comment]
I had the same issue putting Energy Cell (reward) next to a fluxduct and a magmatic dynamo. In addition, the game crashed right after the cell was placed, but before it disappered from my inventory. So when I restarted the game I had one placed energy cell and one duplicated energy cell in my inventory.
[crash-2019-06-25_19.02.15-client.txt](https://pastebin.com/zDqNeXvQ)
[crash-2019-06-25_19.02.14-server.txt](https://pastebin.com/iDxDYN2G)

**Comment by RubikMonat** [comment]
Had the same issue, Powering a MFR mob killer thing. Mobs glitched out through the walls on restart (not related) and creepers blew me to bits when the chunk reloaded. A bad day. However the energy cell now behaves fine.
