### ISSUE TITLE
Outdated betterquesting

### ISSUE THREAD

**Issue by crpmax** [JadedPacks/Agrarian-Skies-2#26]
Hello,
I'am having issues with the new 2.0.2 version with the client and server.
It says the mod betterquesting is outdated, minimum version 2.0.190 is required.
Client error:
(screen deleted)
Server error:

> cpw.mods.fml.common.MissingModsException: 
Missing Mods:
	betterquesting : [2.0.190,)

	at cpw.mods.fml.common.Loader.sortModList(Loader.java:260) ~[Loader.class:?]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:493) ~[Loader.class:?]
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) ~[FMLServerHandler.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

`The mod questbook (Better Questing Quest Book) requires mod versions [betterquesting@[2.0.190,)] to be available`

Thank you for fix.

**Comment by ghost** [comment]
Launching the pack again will (hopefully) fix this issue. Its due to how we distribute these mods. I'll have a patch out shortly =]
